config/routes.rb
Rails.application.routes.draw do
  resources :concerts do
    resources :reservations, except: [:show]
  end
  devise_for :users, skip: [:password, :registrations]
  root to: 'welcome#index'
  get '/news', to: 'welcome#news'
  get '/video', to: 'welcome#video'
  get '/contact', to: 'welcome#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  has_many :reservations, dependent: :delete_all

  validates :title, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  scope :active, -> { where(active: true) }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :concert
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :concert, presence: true
  validates :name, presence: true
  validates :mail, presence: true, format: {with: VALID_EMAIL_REGEX}
  validates :ticket, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 100 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/youtube.rb
require 'google/apis/youtube_v3'

class Youtube
  @@service = nil
  def initialize
    @@service = Google::Apis::YoutubeV3::YouTubeService.new
    @@service.key = ENV["GOOGLE_API_KEY"]
  end

  def All
    return @@service.list_playlist_items(
      "contentDetails,snippet", 
      max_results:50, 
      playlist_id: "UUASYHw_S6bt_7bUhyWWu61Q").items
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all.order(open_at: :desc)
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:title, :open_at, :start_at, :place, :address, :note, :active)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :index]
  before_action :set_reservation, only: [:edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @concert = Concert.find(params[:concert_id])
    @reservations = Reservation.all
  end

  # GET /reservations/new
  def new
    @concert = Concert.find(params[:concert_id])
    @reservation = @concert.reservations.build
    if @reservation.concert.nil? or !@reservation.concert.active
      redirect_to concerts_index_path
    end
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @concert = Concert.find(params[:concert_id])
    @reservation = @concert.reservations.build(reservation_params)

    respond_to do |format|
      if @reservation.save
        NotificationMailer.send_confirm_to_user(@reservation).deliver_later
        format.html { redirect_to concerts_url, notice: '予約が完了しました。' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to concert_reservations_url, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to concert_reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @concert = Concert.find(params[:concert_id])
      @reservation = @concert.reservations.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:concert_id, :name, :mail, :ticket)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def news
    @concerts = Concert.active
  end

  def video
    @videos = (Youtube.new).All
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/concerts/_form.html.haml
= form_for @concert do |f|
  - if @concert.errors.any?
    - @concert.errors.full_messages.each do |message|
      :javascript
        notifyDanger(#{raw message.to_json});

  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :open_at
    %br
    = f.datetime_select :open_at, class: "form-control", :use_month_numbers => true, :include_blank => true, :minute_step => 5
  .form-group
    = f.label :start_at
    %br
    = f.datetime_select :start_at, class: "form-control", :use_month_numbers => true, :include_blank => true, :minute_step => 5
  .form-group
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group
    = f.label :address
    = f.text_field :address, class: "form-control"
  .form-group
    = f.label :note
    = f.text_area :note, class: "form-control", rows: "10"
  .form-group
    = f.label :active
    = f.check_box :active, class: "form-control"
  %br
  .actions
    = f.submit 'Save', class: "btn btn-success"
    = link_to 'Back', concerts_path, class: "btn btn-secondary"

app/views/concerts/index.html.haml
%section.resume-section.p-3.p-lg-5.d-flex.flex-column
  %h2 Live

  - if @concerts.count == 0
    .subheading.mb-5
      ライブ情報がありません。
  - else
    - @concerts.each do |c|
      .card.mb-3
        .card-body
          %string.d-inline-block.mb-2.text-primary
            = c.start_at.strftime("%Y-%m-%d (%a)")
          %h3.mb-0
            = link_to c, class: "text-dark" do
              = c.title
          %p.card-text
            = c.place
            = " / "
            = c.open_at.strftime("%H:%M") + " OPEN"
            = " / "
            = c.start_at.strftime("%H:%M") + " START"

          .mb-0
            .btn-group
              - if c.active?
                = link_to new_concert_reservation_path(c), class: "btn btn-xs btn-outline-secondary" do
                  %i.fa.fa-calendar
                  予約はこちら
              - if signed_in?
                = link_to edit_concert_path(c), class: "btn btn-xs btn-outline-secondary" do
                  %i.fa.fa-edit
                = link_to c, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-outline-danger" do
                  %i.fa.fa-trash
                = link_to concert_reservations_path(c), class: "btn btn-xs btn-outline-secondary" do
                  %i.fa.fa-list

  - if signed_in?
    .actions
      = link_to 'New', new_concert_path, class: "btn btn-primary"

app/views/concerts/show.html.haml
:coffee
  @initMap = ->
    geo = 
      lat: parseFloat "#{@concert.latitude}"
      lng: parseFloat "#{@concert.longitude}"
    map = new (google.maps.Map)($("#map")[0],
      zoom: 15
      center: geo)
    transitLayer = new (google.maps.TransitLayer)
    transitLayer.setMap map
    marker = new (google.maps.Marker)(
      position: geo
      map: map)
    return

%section.resume-section.p-3.p-lg-5.d-flex.flex-column
  %h2 Live詳細
  %h4 Live名
  .detail.mb-3= @concert.title

  %h4 日程
  .detail.mb-3
    = @concert.open_at.strftime("%Y-%m-%d (%a)")
    = " / "
    = @concert.open_at.strftime("%H:%M") + " OPEN"
    = " / "
    = @concert.start_at.strftime("%H:%M") + " START"

  %h4 場所
  .detail.mb-3
    = @concert.place
    = " / "
    = @concert.address

  .detail.mb-3
    #map

  %h4 備考
  .detail.mb-3= @concert.note.gsub(/\R/, "<br>").html_safe

  .actions
    = link_to '戻る', concerts_path, class: "btn btn-secondary"

%script{ src: "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_API_KEY"]}&callback=initMap", async: "", defer: ""}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "shuntaro", :name => "author"}/
    %title Portal264
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag 'favicon.ico'
    = analytics_init if Rails.env.production?

    = stylesheet_link_tag    'application', media: 'all'
    %link{href: "https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900", rel: "stylesheet"}
    %link{href: "https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i", rel: "stylesheet"}

    = javascript_include_tag 'application'

    %body#page-top
      %nav#sideNav.navbar.navbar-expand-lg.navbar-dark.bg-primary.fixed-top
        %a.navbar-brand.js-scroll-trigger{:href => "/"}
          %span.d-block.d-lg-none Portal264
          %span.d-none.d-lg-block
            = image_tag 'profile.jpg', alt: '', height: '', width: '', class: 'img-fluid img-profile rounded-circle mx-auto mb-2'
        %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarSupportedContent.collapse.navbar-collapse
          %ul.navbar-nav
            %li.nav-item
              = link_to('News', news_path, :class => "nav-link js-scroll-trigger")
            %li.nav-item
              = link_to('Live', concerts_path, :class => "nav-link js-scroll-trigger")
            %li.nav-item
              = link_to('Video', video_path, :class => "nav-link js-scroll-trigger")
            %li.nav-item
              = link_to('Contact', contact_path, :class => "nav-link js-scroll-trigger")
            - if user_signed_in?
              %li.nav-item
                = link_to('Logout', destroy_user_session_path, method: :delete, :class => "nav-link js-scroll-trigger", id: "nav-login")

      .container-fluid.p-0
        = yield

      - if !alert.nil?
        :javascript
          notifyDanger(#{raw alert.to_json});

      - if !notice.nil?
        :javascript
          notifyInfo(#{raw notice.to_json});

app/views/reservations/_form.html.haml
= form_for [@concert, @reservation] do |f|
  - if @reservation.errors.any?
    - @reservation.errors.full_messages.each do |message|
      :javascript
        notifyDanger(#{raw message.to_json});

  %h3
    = "Live名："
    = @reservation.concert.title

  .form-group
    = f.label :name, "お名前"
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :mail, "メールアドレス"
    = f.text_field :mail, class: "form-control"
  .form-group
    = f.label :ticket, "予約枚数"
    = f.number_field :ticket, class: "form-control"
  %br
  .actions
    = f.submit '確定', class: "btn btn-success"
    = link_to '戻る', concerts_path, class: "btn btn-secondary"

app/views/reservations/edit.html.haml
%section.resume-section.p-3.p-lg-5.d-flex.flex-column
  %h2 Edit
  = render 'form'

app/views/reservations/index.html.haml
%section.resume-section.p-3.p-lg-5.d-flex.flex-column
  %h2 Index
  %h3
    = @concert.title

  %table.table.table-hover
    %thead
      %tr
        %th Name
        %th Mail
        %th Ticket
        %th

    %tbody
      - @reservations.each do |reservation|
        %tr
          %td= reservation.name
          %td= reservation.mail
          %td= reservation.ticket
          %td
            .btn-group
              = link_to edit_concert_reservation_path(concert_id: reservation.concert.id, id: reservation.id), class: "btn btn-xs btn-outline-secondary" do
                %i.fa.fa-edit
              = link_to concert_reservation_path(concert_id: reservation.concert.id, id: reservation.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-outline-danger" do
                %i.fa.fa-trash

  .actions
    = link_to 'Back', concerts_path, class: "btn btn-secondary"

app/views/reservations/new.html.haml
%section.resume-section.p-3.p-lg-5.d-flex.flex-column
  %h2 チケット予約フォーム
  = render 'form'

app/views/welcome/contact.html.haml
%section.resume-section.p-3.p-lg-5.d-flex.flex-column
  %h2 Contact

  FacebookかTwitterでメッセージください。

  %br
  %br

  %ul.list-inline.list-social-icons.mb-0
    %li.list-inline-item
      %a{:href => "https://www.facebook.com/acappella.264", target: "_blank"}
        %span.fa-stack.fa-lg
          %i.fa.fa-circle.fa-stack-2x
          %i.fa.fa-facebook.fa-stack-1x.fa-inverse
    %li.list-inline-item
      %a{:href => "https://twitter.com/264acappella", target: "_blank"}
        %span.fa-stack.fa-lg
          %i.fa.fa-circle.fa-stack-2x
          %i.fa.fa-twitter.fa-stack-1x.fa-inverse

app/views/welcome/index.html.haml
%section#about.resume-section.p-3.p-lg-5.d-flex.flex-column
  .my-auto
    %h1.mb-0
      A cappella Group 
      %span.text-primary 264
    .subheading.mb-5
      A Cappella Group no 264(tsu-mu-ji) desu. otona no warufuzake, mitsumeyou. 264 to issho ni paradise!!!!!

    %span.d-block.d-lg-none
      = image_tag 'profile.jpg', alt: '', height: '', width: '', class: 'img-fluid img-profile rounded-circle mx-auto mb-2'
    %br

    %ul.list-inline.list-social-icons.mb-0
      %li.list-inline-item
        %a{:href => "https://www.facebook.com/acappella.264", target: "_blank"}
          %span.fa-stack.fa-lg
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-facebook.fa-stack-1x.fa-inverse
      %li.list-inline-item
        %a{:href => "https://twitter.com/264acappella", target: "_blank"}
          %span.fa-stack.fa-lg
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-twitter.fa-stack-1x.fa-inverse
      %li.list-inline-item
        %a{:href => "https://www.youtube.com/channel/UCASYHw_S6bt_7bUhyWWu61Q", target: "_blank"}
          %span.fa-stack.fa-lg
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-youtube.fa-stack-1x.fa-inverse

app/views/welcome/news.html.haml
%section.resume-section.p-3.p-lg-5.d-flex.flex-column
  %h2 News

  - if @concerts.count == 0
    .subheading.mb-5 
      最新情報がありません。
  - else
    - @concerts.each do |c|
      .card.mb-3
        .card-body
          %string.d-inline-block.mb-2.text-primary
            Live Info
          .mb-1.text-muted
            = c.created_at.strftime("%Y-%m-%d")
          %h3.mb-0
            = link_to c, class: "text-dark" do
              [
              = c.start_at.strftime("%Y-%m-%d (%a)")
              ]
              = c.title
          %p.card-text.mb-auto
            ライブ情報が追加されました。
            チケットのご予約は
            = link_to 'こちら', new_concert_reservation_path(c)
            。

app/views/welcome/video.html.haml
%section.resume-section.p-3.p-lg-5.d-flex.flex-column
  %h2 Video

  - if @videos.count == 0
    .subheading.mb-5
      ライブ情報がありません。
  - else
    - @videos.each do |v|
      .card.flex-md-row.mb-3
        .card-body
          %string.d-inline-block.mb-2.text-primary
            = v.content_details.video_published_at.strftime("%Y-%m-%d (%a)")
          %h4.mb-1.nowrap-ellipsis
            = v.snippet.title
        %a{class: "youtube", href: "https://www.youtube.com/watch?v=#{v.content_details.video_id}", target: "empty"}
          %img{width: "320", height: "180", src: "https://img.youtube.com/vi/#{v.content_details.video_id}/mqdefault.jpg", class: "card-img-right flex-auto d-lg-block", alt: ""}